[package]
name = "randpi"
version = "0.1.0"
authors = ["Muirey03 <tommy.muir@btinternet.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
decimal = "2.1.0"
rand = "0.8.3"